# Generated by Django 4.2.6 on 2023-10-16 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_adminong_activation_key_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminONG',
        ),
    ]
