# Generated by Django 4.2.6 on 2023-11-23 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gotinhas', '0004_gotinhas_anotacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='atividades_fotos/')),
                ('professor', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('turma', models.CharField(max_length=50)),
                ('falta', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gotinhas.gotinhas')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atividades.atividade')),
            ],
        ),
        migrations.AddField(
            model_name='atividade',
            name='alunos',
            field=models.ManyToManyField(through='atividades.Presenca', to='gotinhas.gotinhas'),
        ),
    ]
