# Generated by Django 4.2.6 on 2023-10-16 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gotinhas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gotinha',
            new_name='Gotinhas',
        ),
    ]
