# Generated by Django 4.2.6 on 2023-10-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotinhas', '0003_gotinhas_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='gotinhas',
            name='anotacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
